# default
timeout: 30000
warningThreshold: 10
webhook:
  mention: "@everyone"
  # Discord:content Slack:text
  requestKey: content
useTasks:
  - flic
  - switchbot
  - ewelink
  - hue
batteryTypeNames:
  unknown: 不明
  aa: 単3電池
  aaa: 単4電池
  cr2: CR2
  cr2016: CR2016
  cr2032: CR2032
flic:
  # flicd
  hosts:
    - 192.168.1.30
    - 192.168.1.31
  deviceNames:
    "AG46-B05941": 玄関ドアのボタン
hue:
  # bridge
  host: 192.168.1.158
