# default
timeout: 30000
warningThreshold: 10
webhook:
  mention: "@everyone"
  # Discord:content Slack:text
  requestKey: content
useTasks:
  - switchbot
  - ewelink
  - hue
batteryTypeNames:
  unknown: 不明
  aa: 単3電池
  aaa: 単4電池
  cr2: CR2
  cr2016: CR2016
  cr2032: CR2032
hue:
  # bridge
  host: 192.168.1.158
